version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log/efk:/var/log/efk
    depends_on:
      - server
      - elasticsearch

  server:
    build: .
    volumes:
      - /var/log/efk:/var/log/efk
    ports:
      - "8080:8080"

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
